### ISSUE TITLE
Update Example usage with demo data (megalodon txt files)

### ISSUE THREAD

**Issue by chinmaysharmacs10** [marcpaga/sturgeon#10]
The commands in the read me to run live mode prediction on megalodon txt files do not mention path for probes file. As a result, the code attempts to use the default probes.bed file, which doesn't exist in '/venv/lib/python3.9/site-packages/sturgeon/include/static/' resulting in an error. 

I would suggest to update the run command to include the T2T probes file:

'''
sturgeon live \
-i demo/mega \
-o demo/mega/out_live \
-s megalodon \
--model-files PATH_TO_MODEL_DIR/general.zip \
--probes-file ./venv/lib/python3.9/site-packages/sturgeon/include/static/probes_chm13v2.bed \
--plot-results
'''

**Comment by marcpaga** [comment]
This is a problem due to the addition of probe bed files for chm13 and hg38. This should fix the bug https://github.com/marcpaga/sturgeon/commit/bf2f12211b6305930dc006318b7540bc5dad62f7. I have added the option to pass the desired reference genome as with `predict` https://github.com/marcpaga/sturgeon/commit/67fb704356e3992c71898c468f12b9fdc488633f

**Comment by chinmaysharmacs10** [comment]
Hey @marcpaga,

In your last comment you mentioned "I have added the option to pass the desired reference genome as with predict".

However, the `predict` mode doesn't have a reference genome argument since it takes bed files as input, and bed files are already aligned with the reference genome. Is that the correct understanding?

**Comment by marcpaga** [comment]
Yes, sorry. I meant the `inputtobed` utility.
