### ISSUE TITLE
Adding dorado as source in live mode

### ISSUE THREAD

**Issue by chinmaysharmacs10** [marcpaga/sturgeon#11]
Oxford Nanopore Technologies (ONT) have integrated their new basecaller [Dorado](https://github.com/nanoporetech/dorado) into MinKNOW (the controller software on thier devices, including MinION). I noticed that we must provide source (-s) as input while running the live mode of Sturgeon. However, currently we only have Guppy/Megalodon as options. 

<img width="912" alt="Screenshot 2024-02-13 at 7 39 07 AM" src="https://github.com/marcpaga/sturgeon/assets/35448762/cc8faa1d-051b-41f8-b8ce-a5114b587ae1">

To keep the model up-to-date with the recent developments with ONT, it would be great if Dorado is added as a source in the live mode. 

Given that Dorado also outputs bam files and the underlying service architecture is very similar to Guppy, the code for adding Dorado as source should be fairly straightforward.

**Comment by marcpaga** [comment]
Hi @chinmaysharmacs10, 

We depend on [modbam2bed](https://github.com/epi2me-labs/modbam2bed/tree/master) to be able to extract methylation calls from bam files. Since this project been deprecated, we now recommend the use of [modkit](https://github.com/nanoporetech/modkit/), which is also developed by ONT and should be up-to-date with Dorado.

**Comment by chinmaysharmacs10** [comment]
Hi @marcpaga,

Thank you for your reply. 

Modkit will convert the bam files we get from Dorado to bed files. But I think bed files don't work in the live mode directly.

I did try using bed files with live mode. However, I suppose that live mode only looks for bam files in the input folder and returns the message "Looking for new bam files, so far found 0" if there is no bam file.

I used the bed example files in the demo folder, which is used for the predict mode example, to run live mode. I issued the following command:
`sturgeon live \
-i demo/bed \
-o demo/bed/results_live/ \
-s guppy \
--model-files ./sturgeon/include/models/general.zip \
--probes-file ./venv/lib/python3.9/site-packages/sturgeon/include/static/probes_chm13v2.bed \
--plot-results`

Let me know if you have any inputs on this, or on steps to use bed files in the live mode.

Thanks!

**Comment by marcpaga** [comment]
I understand your problem now. It's a bit complicated to keep the `live` feature in the future, since we depend that for every new bam file `modkit` is called to process it. 

My recommendation would be that you write yourself a script that checks a folder for bam files and then calls `modkit extract` (see readme for a bit more detail), then calls `sturgeon inputtobed -s modkit`, and finally calls `sturgeon predict`. 

We are currently using this approach, and will likely leave the `live` feature as legacy only for megalodon and guppy.

**Comment by chinmaysharmacs10** [comment]
Thank you for your suggestions @marcpaga :) This is exactly the approach I was thinking.

**Comment by chinmaysharmacs10** [comment]
Hi @marcpaga,

Hope you are doing well.

I created the script like you suggested and also managed to get some pod5 files generated by the Minion device. These files are of brain tumor samples. However, I am getting an empty bed file after running the inputtobed command. 

These are the steps in my pipeline:
1. Generating bam file from pod5 files using command --> "dorado basecaller hac,5mCG_5hmCG pod5_folder_path > bam_file_path"
2. Modkit file from bam file using command --> "modkit extract bam_file_path modkit_txt_file_path"
3. Converting modkit file to bed file using command --> "sturgeon inputtobed -i modit_file_path -o bed_file_directory -s modkit"
4. Finally, running strugeon predict using command --> "sturgeon predict -i bed_file_directory -o output_directory --model_files model_path --plot_results"

I am unable to understand why I am getting an empty bed file. The pod5 files have been tested for methylation presence by others and have methylated CpG sites. 

Maybe I am issuing incorrect commands. I would really appreciate your help in resolving this.

Thanks,
Chinmay

**Comment by marcpaga** [comment]
Hi @chinmaysharmacs10,

From your dorado command my guess is that the data is not mapped. The reads have to be mapped so that we know which CpG sites are which. Check the alignment section https://github.com/nanoporetech/dorado?tab=readme-ov-file#alignment for commands on how to align your data.

Also very imporant, align the data to the T2T reference genome for best results: https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz

If this does not solve the issue, could you please paste perhaps the top 20 rows of the output of modkit, maybe that can help me see what would be the problem.

**Comment by chinmaysharmacs10** [comment]
Thank you for pointing that out Marc. I missed aligning my bam files.

Yes, now with the data aligned to the T2T reference genome, I am able to get good CpG site coverage.

Appreciate your help, and will reach out if I have more questions :) Your model has me really excited and I wish to leverage in this end-to-end pipeline.

**Comment by minw2828** [comment]
Hi @marcpaga, 

I just finished reading your Sturgeon paper yesterday. Impressive work! 

Is it because the results shown in your publication were trained on T2T, and hence you said "for best results" above? 

If I proceeded with `sturgeon/include/static/probes_hg38.bed`, would you have any advice on what issues it might encounter downstream, perhaps apart from a lower sensitivity due to the missing informative probes across versions of the reference genome? 

Many thanks,
Min

**Comment by marcpaga** [comment]
Hi @minw2828,

thank you for your words! 
There is a loss of 26 probes in the hg38 version compared to the t2t version (See https://github.com/UMCUGenetics/sturgeon/issues/2). We have not tested extensively, but for a few samples we did not notice any result differences. In the context of the >400.000 probes, it is very unlikely that 26 will have a significant impact in performance.

Best,
Marc

**Comment by minw2828** [comment]
Hi @marcpaga,

Thank you for responding so quickly and providing helpful comments! 

Cheers, 
Min
