### ISSUE TITLE
support for modkit pileup

### ISSUE THREAD

**Issue by rowanhowellGE** [marcpaga/sturgeon#12]
Hi,

Would it be possible to add support to run `inputtobed` from the output of `modkit pileup` rather than just `modkit extract`? 

For reasonably large bam files, pileup is quicker and produces much smaller output files than extract.

I am also wondering if we need the `modkit adjust-mods` step if we use the `--ignore h` flag for  `modkit extract`/`pileup` to produce a table without 5hmc calls? 

Thanks

**Comment by marcpaga** [comment]
Hi @rowanhowellGE,

I have never used `modkit pileup` myself, but after looking at the documentation I don't see why it shouldn't be possible. I'll try to add support for it next week. In essence, we do the pileup ourselves when we do the `inputtobed`. 

In principle you do not have to run `adjust-mods` if you do not have `h` calls. However, Sturgeon is trained on microarray data, which follows bi-sulfite conversion. In this type of measurement, 5hmC is also measured as 5mC, so merging the scores of the two modifications as 5mC would resemble the most the microarray data. We have tested this in a few samples ourselves, and haven't seen any differences between ignoring and adjusting, but we have opted to adjust them in our pipeline since it would resemble the most the training data.

**Comment by rowanhowellGE** [comment]
Ok thanks, just looking at modkit documentation, `pileup` in particular has the `--combine-mods` flag which will merge 5hmC and 5mC calls as desired (https://github.com/nanoporetech/modkit/blob/master/collapse.md)

**Comment by marcpaga** [comment]
Hi @rowanhowellGE,

I have pushed an update with the pileup support, you should be able to run now.
`sturgeon inputtobed -i MODKIT_PILEUP_FILE -o OUTPUT_FILE -s modkit_pileup`

Please let me know if you encounter any issues.

**Comment by rowanhowellGE** [comment]
Thanks, this format is slightly different to the command for `-s modkit`, as -o gives OUTPUT_FILE, rather than OUTPUT_DIR, is that intentional?

I'm wondering as `predict` requires an input directory rather than file right?

**Comment by marcpaga** [comment]
It is intentional, since with modkit_pileup we know it's a single file. 

`predict` should work if you give it a single file, a directory with a single file, or a directory with multiple files.

**Comment by rowanhowellGE** [comment]
Hi,

Ok I have been able to make this feature work now but a couple of notes:
- Although I can specify an output file for `inputtobed`, it no longer removes the out.bed.tmp file after running. Additionally, if you try and overwrite existing `inputtobed` output in the same location then it throws the following error:
`NotADirectoryError: [Errno 20] Not a directory: out.bed`
This suggests that using a file rather than directory as output is not fully integrated into the rest of the code.
- When I rebuilt my docker image to include the latest version of sturgeon with modkit pileup support, I inadvertently installed numpy v2.0, which was released last month. This causes errors in the `sturgeon predict` command. Not really an issue with your code per se, but you may want to specify somewhere that numpy v2.0 isn't compatible. 

Thanks for adding this feature though, drastically reduces the memory footprint of running sturgeon on large bam files!
Rowan

**Comment by marcpaga** [comment]
Thanks for the notes, I'll see if I can debug this.
